import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "../../components/theme-provider";
import "./globals.css";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MY WORLD",
  description: "Generated by YouSungBlade",
  icons: "/WorldLogo.png",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
